apiVersion: v1
kind: Secret
metadata:
  name: backend-base-secret
data:
  SECRET_JWT: "U2VjcmV0X0p3dF9Gb3JfRGV2ZWxvcG1lbnRfRW52aXJvbm1lbnQ="
  DB_CONNECTION_STRING: "SG9zdD1wb3N0Z3JlcztQb3J0PTU0MzI7UG9vbGluZz10cnVlO0RhdGFiYXNlPUJhY2tFbmREZXY7VXNlciBJZD1wb3N0Z3JlcztQYXNzd29yZD1wb3N0Z3Jlczs="
  PATH_JSON: "Z2NwLWtleS5qc29u"
  PROJECT_ID: ""
  BUCKET: "dGVzdGUtYmFja2VuZA=="
